logging:
    path: c:/temp/spring-learn/logs

# for PostgreSQL database
spring:
    datasource:
#        driver-class-name: org.h2.Driver
        url: "jdbc:postgresql://10.227.213.112/sa"
        username: sa
        password: sa
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    flyway:
        clean-disabled: true